### ISSUE TITLE
Unable to `include RSpec::GraphqlMatchers::TypesHelper`

### ISSUE THREAD

**Issue by khamusa** [khamusa/rspec-graphql_matchers#1]
Using `v0.2.0`

**Comment by StanBoyet** [comment]
Hi,

How do you use the gem without this? I tried including it but keep having `NameError: uninitialized constant RSpec::GraphqlMatchers`

**Comment by khamusa** [comment]
Hi @StanBoyet ,

I haven't really worked on this Issue for many reasons. Mainly I'm thinking it's not a good idea as a feature, as the Graphql-ruby creator himself has been proposing to avoid the usage of `types` and instead using the type constants directly.

there are quite a few ways to work around this. The first one, if you want to use the types variable, is to define it yourself. 

`types` is basically a shortcut to `GraphQL::Define::TypeDefiner.instance`, so you can define a method called `types` or assign `GraphQL::Define::TypeDefiner.instance` to a variable called types, depending on your context / test runner.

However, after writing quite a lot of specs on types, I believe the main purpose of these is to help you to avoid breaking changes on your api interface. For that purpose, a better idea is to specify types directly as strings instead of using the constants. Suppose you have a type `User`, and you write your specs using a ruby constant `UserType`. At some point you decide to rename the `User` type to `Player`, but you keep the same constant throught your application. If you wrote your specs using the constant `UserType`, they will still pass, but this is a potentially breaking change as clients may have defined queries using variables of type `User`, which is now `Player`.

Hope this helps :)

**Comment by StanBoyet** [comment]
Hey @khamusa,

Thanks for your answer, I get it now. 
I proposed a PR to remove the line where you suggest to add it to the `spec_helper.rb` so newcomers don't get confused 😃  PR #5

Thanks for your work,

Cheers

**Comment by khamusa** [comment]
I really thought I had already removed that line! Thank you ;)

I'll close this issue now.
