### ISSUE TITLE
add has_metadata matcher on object type

### ISSUE THREAD

**Issue by marcgreenstock** [khamusa/rspec-graphql_matchers#12]
Like Field, anything that includes [InstanceDefinable](http://www.rubydoc.info/gems/graphql/1.6.6/GraphQL/Define/InstanceDefinable) can have metadata.

It would be great to have test like:

```ruby
it { is_expected.to have_metadata({foo: 'bar'}) }
```

**Comment by khamusa** [comment]
This is already supported for a while for those using graphql 1.7.x. I'm closing this issue for now.
