### ISSUE TITLE
Type specs fail after graphql-ruby changed behavior of Type classes

### ISSUE THREAD

**Issue by kriskelly** [khamusa/rspec-graphql_matchers#18]
Seems like you can't use this particular style of testing anymore:

```
describe Types::User do
  # avail type definer in our tests
  types = GraphQL::Define::TypeDefiner.instance

  it 'has an :email field of String type' do
    expect(subject).to have_field(:email).that_returns(!types.String)
  end
end
```
That spec now raises the error:
```
NoMethodError:
  protected method `new' called for Types::User:Class
```
This is due to an upstream change where you can't call `.new` anymore and must call `.authorized_new` instead. I had some trouble trying to figure out how to actually successfully call that method in `subject` so thought I'd give a heads up here in case anyone is trying to use this gem for this type of spec.

**Comment by schonert** [comment]
@kriskelly thanks for the heads up!
I came around this by defining the subject in in the top

```ruby
describe Types::User do
  let(:subject) { Types::User }
  
  # ...

end
```

**Comment by khamusa** [comment]
You're absolutely right. The latest gem versions brings lots of fixes and, particularly, support to testing fields defined using the new class based api as well as the legacy api. The examples in the readme have also been updated to include `subject { described_class }` whenever necessary.

Let me know if you still have issues with this, for now I'm closing this issue.
