### ISSUE TITLE
Specs fail with "types" syntax

### ISSUE THREAD

**Issue by kassi** [khamusa/rspec-graphql_matchers#19]
I'm using `graphql-ruby` 1.8 and I have a `GameType` defined as well as a `GameQueryType` like this

```ruby
module Types
  class GameType < Types::BaseObject
    ...
  end
end

module Types
  GameQueryType = GraphQL::ObjectType.define do
    name 'GameQueryType'
    description 'The games query type'
    field :games, types[Types::GameType], 'returns all games' do
      resolve ->(_obj, _args, _ctx) { Game.all }
    end
  end
end
```

When I write a spec

```ruby
it "has a :games field that returns a list of games" do
  expect(subject).to have_field(:games).that_returns(types[Types::GameType])
end
```
it fails with

> expected Query to define field `games`, of type `#<GraphQL::Schema::List:0x00007f83730fdf90>`, but the type was `[Game]`.

Only

```ruby
it "has a :games field that returns a list of games" do
  expect(subject).to have_field(:games).that_returns("[Game]")
end
```

works, but this is not the right way of writing in my opinion.

If I define my `GameTypeQuery` like

```ruby
module Types
  class GameQueryType < Types::BaseObject
    graphql_name 'GameQueryType'
    description 'The games query type'

    field :games, [Types::GameType], 'returns all games', null: true
  end
end
```
then
```
it "has a :games field that returns a list of games" do
  expect(subject).to have_field(:games).that_returns(types[Types::GameType])
end
```
produces
> expected Query to define field `games`, of type `#<GraphQL::Schema::List:0x00007f836b612d58>`, but the type was `#<GraphQL::Schema::List:0x00007f836af9b7e0>`

while
```ruby
it "has a :games field that returns a list of games" do
  expect(subject).to have_field(:games).that_returns([Types::GameType])
end
```
produces
> expected Query to define field `games`, of type `[Types::GameType]`, but the type was `#<GraphQL::Schema::List:0x00007f8373483110>`

Maybe I'm doing it wrong but I guess something is broken here.
How to write it correctly?

**Comment by khamusa** [comment]
Please check the latest version, this issue should have been fixed.

As a side note, i'm pushing towards using string to define expected types, since the gem itself is moving towards abolishing `types.X` notation (for instance, using the exclamation mark to create a non null field will not work on objects defined using the new class-based api).
