### ISSUE TITLE
Cannot use with new version of graphql gem

### ISSUE THREAD

**Issue by ksykulev** [khamusa/rspec-graphql_matchers#2]
The graphql gem is currently at version 1.3.0.

However, the gemspec states the graphql dependency has to be '< 1'
https://github.com/khamusa/rspec-graphql_matchers/blob/master/rspec-graphql_matchers.gemspec#L23

I loosened the runtime dependency:
`spec.add_runtime_dependency     'graphql', '>= 0.9', '< 2'`
Then ran the tests and everything passed. Any reason not to bump the dependency up to support the new version of graphql?

**Comment by khamusa** [comment]
@ksykulev thanks for pointing that out. This is now fixed and the new version has already been published to Rubygems. cheers!
