### ISSUE TITLE
Supporting version 1.9 ?

### ISSUE THREAD

**Issue by thornomad** [khamusa/rspec-graphql_matchers#27]
Hi there - just began doing some GraphQL development on Rails this week with the `graphql-ruby` gem (1.9x).   Noticed that it's version limited to 1.8.

I quickly cloned this repo and removed the version limit in the gemspec file.  It seems to be working with the project I am on.

I also ran `rspec` from your project root and the tests all passed.  

Could we get a version bump?

**Comment by khamusa** [comment]
@thornomad, we released yesterday a new version.
