### ISSUE TITLE
Convert :field_name to 'fieldName' automaticallly

### ISSUE THREAD

**Issue by yagudaev** [khamusa/rspec-graphql_matchers#28]
First, of, thank you for the gem :). It reminds me the joy of Shoulda, which is an excellent little gem.

I have a small request, is it possible to automatically change the casing to camel case?

Instead of 

```ruby
# this already works, but not very rubyish
it { is_expect.to have_field(:isPublished) }
# what if we allow for this
it { is_expect.to have_field(:is_published) }
```

**Comment by khamusa** [comment]
Hello @yagudaev! I think this would be a nice addition, but I think this behaviour should exist on an opt-in basis. I'll gladly accept a PR, would you be willing to work on this?
