### ISSUE TITLE
Test resolution with property

### ISSUE THREAD

**Issue by khamusa** [khamusa/rspec-graphql_matchers#3]
Add an easy way to test the usage of `property`: `field :public, types.Boolean, property: :is_public`

**Comment by marcgreenstock** [comment]
I'll take a stab at this.

how will something like this work?

```ruby
it { is_expected.to have_a_field(:public).with_property(:is_public) }
```

I think it should also be capable of matching other options too, like `hash_key` and `metadata`.

```ruby
it { is_expected.to have_a_field(:myThing).with_hash_key(:my_thing).with_metadata(foo: :bar, baz: true) }
```

**Comment by khamusa** [comment]
Nice! This looks good!
